apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-discord
  namespace: growfatlikeme-prom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-discord
  template:
    metadata:
      labels:
        app: alertmanager-discord
    spec:
      containers:
        - name: alertmanager-discord
          image: benjojo/alertmanager-discord:latest
          env:
            - name: DISCORD_WEBHOOK
              value: "https://discord.com/api/webhooks/1402937210117951498/z79PpnykF3Fo46vqlb978tlkZh5cmi_Hk37ZbKC1M7EYnuTWJk4z-KzUojNCaaHQF4J-"
          ports:
            - containerPort: 9094
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-discord
  namespace: growfatlikeme-prom
spec:
  selector:
    app: alertmanager-discord
  ports:
    - port: 9094
      targetPort: 9094
