grafana:
  enabled: true
  persistence:
    enabled: false
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - growfatlikeme-grafana.sctp-sandbox.com
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "growfatlikeme-grafana.sctp-sandbox.com"
  adminPassword: admin123
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://growfatlikeme-prom-prometheus-server.growfatlikeme-prom:80
        access: proxy
      - name: Loki
        type: loki
        url: http://grafana-stack-loki:3100
        access: proxy
        isDefault: true

loki:
  enabled: true
  persistence:
    enabled: false
  config:
    auth_enabled: false
    server:
      http_listen_port: 3100
    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/boltdb-shipper-active
        cache_location: /data/loki/boltdb-shipper-cache
        shared_store: filesystem
      filesystem:
        directory: /data/loki/chunks
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h

promtail:
  enabled: true
  daemonset:
    enabled: true
  config:
    server:
      http_listen_port: 3101
    clients:
      - url: http://grafana-stack-loki:3100/loki/api/v1/push
    scrape_configs:
      # Kubernetes pod logs
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node_name
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container
          - source_labels: [__meta_kubernetes_pod_controller_kind]
            target_label: controller_kind
          - source_labels: [__meta_kubernetes_pod_controller_name]
            target_label: controller_name
          - source_labels: [__meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name]
            target_label: __path__
            separator: /
            replacement: /var/log/pods/*$1/*.log
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
      
      # System logs from nodes
      - job_name: kubernetes-nodes
        static_configs:
          - targets:
              - localhost
            labels:
              job: node-logs
              __path__: /var/log/messages
      
      # Journal logs (systemd)
      - job_name: journal
        journal:
          json: false
          max_age: 12h
          path: /var/log/journal
          labels:
            job: systemd-journal
      
      # Kubernetes audit logs
      - job_name: kubernetes-audit
        static_configs:
          - targets:
              - localhost
            labels:
              job: kubernetes-audit
              __path__: /var/log/audit.log