prometheus-node-exporter:
  enabled: true
kube-state-metrics:
  enabled: false
alertmanager:
  enabled: true
  persistence:
    enabled: false
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: growfatlikeme-alertmanager.sctp-sandbox.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "growfatlikeme-alertmanager.sctp-sandbox.com"
  configFromSecret: ""
  configFileName: alertmanager.yml

alertmanagerFiles:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'job', 'instance']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 30s
      receiver: default-receiver
    receivers:
    - name: default-receiver
      webhook_configs:
        - url: http://alertmanager-discord:9094
          send_resolved: false
    templates:
    - /etc/alertmanager/*.tmpl

serverFiles:
  prometheus.yml:
    rule_files:
      - "/etc/config/custom-rules.yaml"
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090
      - job_name: node-exporter
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - growfatlikeme-prom
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            action: keep
            regex: prometheus-node-exporter
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: "9100"
      - job_name: nginx
        static_configs:
          - targets:
              - ingress-nginx-controller-metrics.ingress-nginx:10254

ruleFiles:
  custom-rules.yaml: |
    groups:
      - name: node-efficiency
        rules:
          - alert: HostCpuIsUnderutilized
            expr: (min by (instance) (rate(node_cpu_seconds_total{mode="idle"}[1h]))) > 0.8
            for: 1d
            labels:
              severity: info
            annotations:
              summary: "Host CPU is underutilized (instance {{ $labels.instance }})"
              description: "CPU load has been < 20% for 10 min. Consider reducing the number of CPUs.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      # Add more rule groups here:
      # - name: memory-alerts
      #   rules:
      #     - alert: HighMemoryUsage
      #       expr: ...
      # - name: disk-alerts
      #   rules:
      #     - alert: DiskSpaceLow
      #       expr: ...

server:
  persistentVolume:
    enabled: false
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - growfatlikeme-prom.sctp-sandbox.com
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "growfatlikeme-prom.sctp-sandbox.com"
